export const ADD_CURRENCY_TO_LIST = 'ADD_CURRENCY_TO_LIST';
export const REMOVE_CURRENCY_FROM_LIST = 'REMOVE_CURRENCY_FROM_LIST';
export const CHANGE_BASE_CURRENCY = 'CHANGE_BASE_CURRENCY';
export const SET_INITIAL_EXCHANGE_RATES = 'SET_INITIAL_EXCHANGE_RATES';